spring:
  datasource:
    url: jdbc:h2:mem:editora
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mvc:
    static-path-pattern: /swagger*


server:
  port: 8085
springdoc:
  api-docs:
    path: /api/documentation
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.vsouza.editora.controllers

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info, metrics
